const productCatalogue = [
  {
    "name": "Objective ECM",
    "description": "EDRMS (Electronic Document Records Management System)",
    "sme": "Ben, Linda",
    "vendor": "OCL (objective Corporation limited)",
    "version": "11.2.2",
    "latestVersion": "Most recent Released Nexsus 2024 R1.6",
    "agency": "OCG\nTreasury\nSBC\nDCITHS\nInfosys (DCS)\nBPB (DCS)",
    "department": "DCS",
    "users": "2618 Licensed users",
    "deployment": "On-premise",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "Salesforce - Investment NSW, SNOW - Infosys, Worker Check - NDIS (OCG), Objective Connect - OCG, LEX - DCITHS ",
    "documentation": "SNOW KNowledge Management Database, Internal Sharepoint Site, Objective Training Environment",
    "licenseType": "Perpertual",
    "renewalTerms": "Multi year ",
    "contractExpiry": "2026-06-30 00:00:00",
    "plannedChanges": "No planned Changes",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "Objective Connect",
    "description": "Secure External Sharing and Collboration of Objective Records",
    "sme": "Ben, Linda",
    "vendor": "OCL (objective Corporation limited)",
    "version": "Evergreen (Never Expires)",
    "latestVersion": "Evergreen (Never Expires)",
    "agency": "OCG",
    "department": "OCG",
    "users": "",
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Evergreen",
    "integrations": "Connect Link - OCG",
    "documentation": "SNOW KNowledge Management Database, Internal Sharepoint Site, Objective Training Environment",
    "licenseType": "Enterprise",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "01-Oct-2025 (Approx)",
    "plannedChanges": "No planned Changes",
    "eol": "Not Officially Announced",
    "eos": "Evergreen"
  },
  {
    "name": "TRIM - Core",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization.",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 9.2,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Telco\nDigital NSW (GCIDO)\nPeople & Culture (P&C)\nPSG (Policy, Strategy & Governance)\nDCS Finance Office\nNSW Fair Trading\nGovernment Shared Services\nBuilding Commissions NSW",
    "department": "DCS",
    "users": 3138,
    "deployment": "On-Premise",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - IPC",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 9.2,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Information and Privacy Commission (IPC)",
    "department": "IPC",
    "users": 70,
    "deployment": "On-Premise",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - L&G",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 10.1,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Liquor & Gaming NSW",
    "department": "Liquor and Gaming NSW",
    "users": 566,
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - LSC",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 9.4,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Long Service Corporation (LSC)",
    "department": "DCS",
    "users": 251,
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - PIC",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 10.1,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Personal Injury Commission (PIC)",
    "department": "DCS",
    "users": 587,
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - Service NSW",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 10.1,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Service NSW",
    "department": "DCS",
    "users": 231,
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - SIRA",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 9.2,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "SIRA ( State Insurance Regulatory Authority)",
    "department": "DCS",
    "users": 2078,
    "deployment": "On-Premise",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - Sptatial",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 10.1,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Spatial Services",
    "department": "DCS",
    "users": 350,
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - Destination NSW",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 10.1,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Destination NSW",
    "department": "DCS",
    "users": "",
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - Place Management",
    "description": "Primary Records Management system used to securely store, manage, and access business records across Organization. ",
    "sme": "Heather, Urva",
    "vendor": "OpenText",
    "version": 9.2,
    "latestVersion": "Version 24.4 (Most recent Release)\nBuild: 574\nPatch Level: Patch 1",
    "agency": "Destination NSW",
    "department": "DCS",
    "users": "",
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "SNOW Knowledge Management, Internal IM Systems Sharepoint Site, TRIM Training Instance's.",
    "licenseType": "Perpetual + Annual Support",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "",
    "eol": "Not Officially Announced",
    "eos": ""
  },
  {
    "name": "TRIM - Revenue",
    "description": "EDRMS Integrated with MARS at Revenue",
    "sme": "Matthew, Michael",
    "vendor": "OpenText - iCog",
    "version": "9.2\nPatch 1\nHotfix 9",
    "latestVersion": "Out of Support by Vendor (Open Text)",
    "agency": "Revenue NSW",
    "department": "DCS",
    "users": 1486,
    "deployment": "AC3 (Cloud)",
    "status": "Active",
    "upgradeFrequency": "",
    "integrations": "Crown Jewel Application, Integrated with primary application at Revenue Digital ",
    "documentation": "Stored In Revenue TRIM, Test UAT Training Environment",
    "licenseType": "Ongoing Maintenance Agreement",
    "renewalTerms": "Annual Renewal ",
    "contractExpiry": "2025-07-01 00:00:00",
    "plannedChanges": "No planned Changes",
    "eol": "Currently Out of Support by Vendor (OpenText)",
    "eos": "Currently Out of Support by Vendor (OpenText)"
  },
  {
    "name": "eApprovals",
    "description": "The eApprovals system is a digital workflow tool used to streamline the review and approval of documents, forms, and requests within an organisation. It provides a secure, trackable, and paperless process for managing approvals efficiently.",
    "sme": "Sammie Orchard, Elisha Beatty",
    "vendor": "Bay Technologies",
    "version": "MINCOR 4.65.1349",
    "latestVersion": "v4.70",
    "agency": "(Inactive) Corporate Services (CS)\nBetter Regulation Division (BRD)\nBuilding Commission\nDCS GIPA\nDigital NSW\nGovernment Shared Services\nIndependent Pricing and Regulatory Tribunal (IPART)\nIndependent Review Office (IRO)\nInformation and Privacy COmmission NSW (IPC)\nMinisterial Services\nMO Approve\nNSW Fair Trading & Regulatory Services\nNSW Telco Authority\nParliamentary Services\nPeople and Culture (P&C)\nPersonal Injury Commission (PIC)\nPolicy, Strategy & Governance (PS&G)\nPortfolio Finance\nProcurement\nRevenue NSW (RNSW)\nSafeWork NSW\nSecretary's Office\nService NSW (SNSW), BDM & LSC\nSmall Business Commission\nState Insurance Regulatory Authority (SIRA)\n(blank)",
    "department": "DCS",
    "users": 3000,
    "deployment": "Cloud",
    "status": "Active",
    "upgradeFrequency": "Ad-hoc",
    "integrations": "",
    "documentation": "Sharepoint",
    "licenseType": "",
    "renewalTerms": "Multi Year",
    "contractExpiry": "2026-01-14 00:00:00",
    "plannedChanges": "No Planned Changes",
    "eol": "Not Officially Announced",
    "eos": ""
  }
];

export default productCatalogue;
